/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import core.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 14400
 */
public class CheckIn extends javax.swing.JFrame {

    Library library = new Library();
    ArrayList<Item> itemlist = new ArrayList<Item>(){};
    Item item;
    Loan loan;
    Account account = new Account();
    
    /**
     * Creates new form ItemsActivity
     */
    public CheckIn() {
        initComponents();
        borrower_panel.setVisible(false);
        item_id_input.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        checkin_complete_dialog = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        ok_complete_button = new javax.swing.JButton();
        borrower_panel = new javax.swing.JPanel();
        check_member_exist_button = new javax.swing.JButton();
        borrower_id_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accountNo_input = new javax.swing.JTextField();
        add_borrower_button = new javax.swing.JButton();
        update_borrower_button = new javax.swing.JButton();
        delete_borrower_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        address_input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        item_doesnt_exist_message = new javax.swing.JLabel();
        message_from_server_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        surname_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        password_input = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        item_id_input = new javax.swing.JTextField();
        add_item_button = new javax.swing.JButton();
        item_doesnt_exist = new javax.swing.JLabel();
        return_items_button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        find_item = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkout_items_display = new javax.swing.JTextArea();
        checkout_items = new javax.swing.JScrollPane();
        item_display = new javax.swing.JTextArea();
        total_items_display = new javax.swing.JLabel();
        onloan_item_message = new javax.swing.JLabel();
        error_borrower_id = new javax.swing.JLabel();
        menu_button = new javax.swing.JButton();

        checkin_complete_dialog.setSize(new java.awt.Dimension(400, 200));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("items successfully returned");

        ok_complete_button.setText("OK");
        ok_complete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_complete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkin_complete_dialogLayout = new javax.swing.GroupLayout(checkin_complete_dialog.getContentPane());
        checkin_complete_dialog.getContentPane().setLayout(checkin_complete_dialogLayout);
        checkin_complete_dialogLayout.setHorizontalGroup(
            checkin_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkin_complete_dialogLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(checkin_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkin_complete_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkin_complete_dialogLayout.createSequentialGroup()
                        .addComponent(ok_complete_button)
                        .addGap(171, 171, 171))))
        );
        checkin_complete_dialogLayout.setVerticalGroup(
            checkin_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkin_complete_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ok_complete_button)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        borrower_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrower_panel.setEnabled(false);

        check_member_exist_button.setText("check if member exists");
        check_member_exist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_member_exist_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Borrower ID");

        jLabel2.setText("Name");

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone");

        jLabel4.setText("AccountNo");

        accountNo_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNo_inputActionPerformed(evt);
            }
        });

        add_borrower_button.setText("Add");
        add_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_borrower_buttonActionPerformed(evt);
            }
        });

        update_borrower_button.setText("Update");
        update_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_borrower_buttonActionPerformed(evt);
            }
        });

        delete_borrower_button.setText("Delete");
        delete_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_borrower_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        item_doesnt_exist_message.setForeground(new java.awt.Color(255, 0, 51));

        jLabel8.setText("Surname");

        surname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_inputActionPerformed(evt);
            }
        });

        username_label.setText("Username");

        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        javax.swing.GroupLayout borrower_panelLayout = new javax.swing.GroupLayout(borrower_panel);
        borrower_panel.setLayout(borrower_panelLayout);
        borrower_panelLayout.setHorizontalGroup(
            borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrower_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrower_id_input)
                    .addComponent(check_member_exist_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address_input)
                    .addComponent(email_input)
                    .addComponent(phone_input)
                    .addComponent(accountNo_input)
                    .addGroup(borrower_panelLayout.createSequentialGroup()
                        .addGroup(borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(borrower_panelLayout.createSequentialGroup()
                                .addComponent(add_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(borrower_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(item_doesnt_exist_message, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addComponent(surname_input)
                    .addComponent(name_input)
                    .addGroup(borrower_panelLayout.createSequentialGroup()
                        .addGroup(borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(username_label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(message_from_server_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_input)
                    .addComponent(password_input)))
        );
        borrower_panelLayout.setVerticalGroup(
            borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrower_panelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(item_doesnt_exist_message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrower_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_member_exist_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountNo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message_from_server_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(borrower_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_borrower_button)
                    .addComponent(update_borrower_button)
                    .addComponent(delete_borrower_button)))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("RETURN ITEMS");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);

        jLabel9.setText("Item ID");

        item_id_input.setText("apple123");

        add_item_button.setText("add item");
        add_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_buttonActionPerformed(evt);
            }
        });

        item_doesnt_exist.setForeground(new java.awt.Color(255, 0, 51));

        return_items_button.setText("RETURN ITEMS");
        return_items_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_items_buttonActionPerformed(evt);
            }
        });

        jLabel12.setText("Items to return");

        find_item.setText("find item");
        find_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_itemActionPerformed(evt);
            }
        });

        checkout_items_display.setColumns(20);
        checkout_items_display.setRows(5);
        jScrollPane2.setViewportView(checkout_items_display);

        item_display.setColumns(20);
        item_display.setRows(5);
        checkout_items.setViewportView(item_display);

        total_items_display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        onloan_item_message.setForeground(new java.awt.Color(255, 0, 0));

        error_borrower_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        error_borrower_id.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item_doesnt_exist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(item_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(find_item, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(error_borrower_id, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(return_items_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkout_items)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_items_display, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(add_item_button)
                                .addGap(31, 31, 31)
                                .addComponent(onloan_item_message, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_doesnt_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find_item))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkout_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(onloan_item_message, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_button))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_items_display, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(error_borrower_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(return_items_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jLabel12.getAccessibleContext().setAccessibleName("Items to return");

        menu_button.setText("MENU");
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrower_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_button)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(menu_button))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrower_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_borrower_buttonActionPerformed
        // TODO add your handling code here:
        int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String message_confirmation = library.removeAccount(borrowerID);
        message_from_server_label.setText(message_confirmation);

    }//GEN-LAST:event_delete_borrower_buttonActionPerformed

    private void update_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_borrower_buttonActionPerformed
        // TODO add your handling code here:
       int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String name = name_input.getText();
        String surname = surname_input.getText();
        String address = address_input.getText();
        String email = email_input.getText();
        int phone = Integer.parseInt(phone_input.getText());
        int accountNo = Integer.parseInt(accountNo_input.getText());
        String username = username_input.getText();
        String password = password_input.getText();
        Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
        String message_from_server = library.updateBorrower(borrower);
        message_from_server_label.setText(message_from_server);
        borrower_id_input.setText("");
        name_input.setText("");
        surname_input.setText("");
        address_input.setText("");
        email_input.setText("");
        phone_input.setText("");
        accountNo_input.setText("");
        username_input.setText("");
        password_input.setText("");

    }//GEN-LAST:event_update_borrower_buttonActionPerformed

    private String getCurrentDate(){
        Date date = new Date();
        String strDateFormat = "dd:mm:y";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        return formattedDate;
        
    }
    private void add_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_borrower_buttonActionPerformed
        // TODO add your handling code here:
        int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String name = name_input.getText();
        String surname = surname_input.getText();
        String address = address_input.getText();
        String email = email_input.getText();
        int phone = Integer.parseInt(phone_input.getText());
        int accountNo = Integer.parseInt(accountNo_input.getText());
        String username = username_input.getText();
        String password = password_input.getText();
        String openingDate = this.getCurrentDate();
        int openingBalance = 0;
        Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
        Account account = new Account(accountNo, openingBalance, openingDate, borrower);
        String message_from_server = library.addAccount(account);
        message_from_server_label.setText(message_from_server);
        borrower_id_input.setText("");
        name_input.setText("");
        surname_input.setText("");
        address_input.setText("");
        email_input.setText("");
        phone_input.setText("");
        accountNo_input.setText("");
        username_input.setText("");
        password_input.setText("");

    }//GEN-LAST:event_add_borrower_buttonActionPerformed

    private void accountNo_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNo_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNo_inputActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void check_member_exist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_member_exist_buttonActionPerformed
        // TODO add your handling code here:
        message_from_server_label.setText("");
        int borrower_id = Integer.parseInt(borrower_id_input.getText());        
        ArrayList<Borrower> borrowerlist = library.getBorrowerInformation(borrower_id);
        if (borrowerlist.size()==0){
            item_doesnt_exist_message.setText("borrower account doesn't exist");
            name_input.setText("");
            surname_input.setText("");
            address_input.setText("");
            email_input.setText("");
            phone_input.setText("");
            accountNo_input.setText("");
            username_input.setText("");
            password_input.setText("");
        }else{
            Borrower borrower = borrowerlist.get(0);
            item_doesnt_exist_message.setText("");
            name_input.setText(borrower.getName());
            surname_input.setText(borrower.getSurname());
            address_input.setText(borrower.getAddress());            
            email_input.setText(borrower.getEmail());
            phone_input.setText(Integer.toString(borrower.getPhone()));
            accountNo_input.setText(Integer.toString(borrower.getAccountNo()));
            username_input.setText(borrower.getUsername());
            password_input.setText(borrower.getPassword());
            
        }

    }//GEN-LAST:event_check_member_exist_buttonActionPerformed

    private void surname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_inputActionPerformed

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

//    private String getDueDate(){
//      int loanPeriod = 0;
//        if (item.getType()=="book"){
//           loanPeriod=3;
//        }
//        else{
//            loanPeriod = 2;
//        }
//      Date d1 = new Date();
//      Calendar cl = Calendar. getInstance();
//      cl.setTime(d1);
//      cl. add(Calendar.DATE, loanPeriod);
//      String duedate = cl.getTime().toString();
//      return duedate;
//    }
    
    private String getDateNow(){
        Date date = new Date();
        String strDateFormat = "d-MM-yyyy";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        return formattedDate;       
    }
    
    private long calculateOverdue() throws ParseException{
        String currentDate = getDateNow();
        Loan loan = new Loan(){};
        String dueDate = loan.getDueDateForFineCalculation(item_id_input.getText());
        SimpleDateFormat dateFormat = new SimpleDateFormat( "d-MM-yyyy" );
        Calendar cal= Calendar.getInstance();
        cal.setTime(dateFormat.parse(currentDate));
        Calendar cal2 = Calendar.getInstance();
        cal2.setTime(dateFormat.parse(dueDate));
        //cal.add( Calendar.DATE, loanPeriod );
        
        long daysBetween = ChronoUnit.DAYS.between(cal.toInstant(), cal2.toInstant());
        return daysBetween;
    }
    
    private long chargeFine(Item item) throws ParseException{
        long noOfDaysOverdue = calculateOverdue();
        long fineamount = 0;
        String itemType = item.getType();
        if (itemType.toLowerCase()=="book"){
            fineamount = noOfDaysOverdue * 1;
        }
        else {
            fineamount = noOfDaysOverdue * 2;
            
        }
        return fineamount;
        
    }
    
    private void ok_complete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_complete_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        checkin_complete_dialog.setVisible(false);
        new MenuActivity().setVisible(true);
    }//GEN-LAST:event_ok_complete_buttonActionPerformed

    private void find_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_itemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        item_display.setText("");
        item_doesnt_exist.setText("");
        onloan_item_message.setText("");

        String item_id = item_id_input.getText();
        System.out.print(item_id);
        item = library.getItem(item_id);
        if (item==null){
            item_doesnt_exist.setText("item doesn't exist");
            item_display.setText("");

        }else{
            item_doesnt_exist_message.setText("");
            String item_info = item.itemToString();
            //            String title = item.getTitle();
            //            String author = item.getAuthor();
            //            String keywords = item.getKeywords();
            //            String type = item.getType();
            //            String status = item.getStatus();
            //            String item_info = "Title: " + title + "\nAuthor: " + author + "\nKeywords: " + keywords + "\nType: " + type + "\nStatus: " + status;
            item_display.setText(item_info);
            Loan loan = new Loan(){};
            String dueDate = loan.getDueDateForFineCalculation(item.getIdentifier());
            item_display.append("\nDue Date: "+dueDate);

        }
    }//GEN-LAST:event_find_itemActionPerformed

    private void return_items_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_items_buttonActionPerformed
        // TODO add your handling code here:


        if (itemlist.isEmpty()){
            error_borrower_id.setText("error: no items  to check out");
        }
        else{

                //change status to available
                for (Item item : itemlist){
                    item.updateStatus(item.getIdentifier(), "IN");
                    library.removeLoan(item.getIdentifier());
                }
                checkin_complete_dialog.setVisible(true);
            
        }

    }//GEN-LAST:event_return_items_buttonActionPerformed

    private void add_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_buttonActionPerformed
        // TODO add your handling code here:
        error_borrower_id.setText("");
        long overdue = 0;
        try {
            overdue = calculateOverdue();
        } catch (ParseException ex) {
            Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if ("IN".equals(item.getStatus())){
            onloan_item_message.setText("cannot add: item is already IN");         
        }
        else{
            itemlist.add(item);
            try {
                long fineamount = this.chargeFine(item);
                loan = new Loan();
                String borrowerID = loan.getBorrowerIDForCheckIn(item.getIdentifier());
                int accountNo = account.getAccountNumber(borrowerID);
                account.debitAmount(accountNo, fineamount);
                checkout_items_display.append(item.checkoutItemToString()+"\n");
                checkout_items_display.append("Overdue: " + Long.toString(overdue));
            } catch (ParseException ex) {
                Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            int totalItems = itemlist.size();
            //total_items_display.setText("TOTAL ITEMS TO RETURN: " + Integer.toString(totalItems));
            
        }
    }//GEN-LAST:event_add_item_buttonActionPerformed

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuActivity().setVisible(true);
    }//GEN-LAST:event_menu_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNo_input;
    private javax.swing.JButton add_borrower_button;
    private javax.swing.JButton add_item_button;
    private javax.swing.JTextField address_input;
    private javax.swing.JTextField borrower_id_input;
    private javax.swing.JPanel borrower_panel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton check_member_exist_button;
    private javax.swing.JDialog checkin_complete_dialog;
    private javax.swing.JScrollPane checkout_items;
    private javax.swing.JTextArea checkout_items_display;
    private javax.swing.JButton delete_borrower_button;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel error_borrower_id;
    private javax.swing.JButton find_item;
    private javax.swing.JTextArea item_display;
    private javax.swing.JLabel item_doesnt_exist;
    private javax.swing.JLabel item_doesnt_exist_message;
    private javax.swing.JTextField item_id_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu_button;
    private javax.swing.JLabel message_from_server_label;
    private javax.swing.JTextField name_input;
    private javax.swing.JButton ok_complete_button;
    private javax.swing.JLabel onloan_item_message;
    private javax.swing.JTextField password_input;
    private javax.swing.JTextField phone_input;
    private javax.swing.JButton return_items_button;
    private javax.swing.JTextField surname_input;
    private javax.swing.JLabel total_items_display;
    private javax.swing.JButton update_borrower_button;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
