/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import core.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 14400
 */
public class OverdueActivity extends javax.swing.JFrame {

    Library library = new Library();

    ArrayList<Item> itemlist = new ArrayList<Item>(){};
    Item item;
    HashMap<Integer, ArrayList> accountDetails = new HashMap<Integer, ArrayList>();  
    Account account = new Account(){};
    int balance = 0;/**
     * Creates new form ItemsActivity
     */
    public OverdueActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        checkout_complete_dialog = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        ok_complete_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        check_member_exist_button = new javax.swing.JButton();
        borrower_id_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accountNo_input = new javax.swing.JTextField();
        add_borrower_button = new javax.swing.JButton();
        update_borrower_button = new javax.swing.JButton();
        delete_borrower_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        address_input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        item_doesnt_exist_message = new javax.swing.JLabel();
        message_from_server_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        surname_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        password_input = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        item_id_input = new javax.swing.JTextField();
        add_item_button = new javax.swing.JButton();
        item_doesnt_exist = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        finish_checkout_button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        find_item = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkout_items_display = new javax.swing.JTextArea();
        checkout_items = new javax.swing.JScrollPane();
        item_display = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        total_items_display = new javax.swing.JLabel();
        onloan_item_message = new javax.swing.JLabel();
        error_borrower_id = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fine_amount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        amount_to_pay_input = new javax.swing.JTextField();
        pay_button = new javax.swing.JButton();

        checkout_complete_dialog.setSize(new java.awt.Dimension(400, 200));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("checkout complete");

        ok_complete_button.setText("OK");
        ok_complete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_complete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkout_complete_dialogLayout = new javax.swing.GroupLayout(checkout_complete_dialog.getContentPane());
        checkout_complete_dialog.getContentPane().setLayout(checkout_complete_dialogLayout);
        checkout_complete_dialogLayout.setHorizontalGroup(
            checkout_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkout_complete_dialogLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(checkout_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkout_complete_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkout_complete_dialogLayout.createSequentialGroup()
                        .addComponent(ok_complete_button)
                        .addGap(170, 170, 170))))
        );
        checkout_complete_dialogLayout.setVerticalGroup(
            checkout_complete_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkout_complete_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ok_complete_button)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);

        check_member_exist_button.setText("check if member exists");
        check_member_exist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_member_exist_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Borrower ID");

        jLabel2.setText("Name");

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone");

        jLabel4.setText("AccountNo");

        accountNo_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNo_inputActionPerformed(evt);
            }
        });

        add_borrower_button.setText("Add");
        add_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_borrower_buttonActionPerformed(evt);
            }
        });

        update_borrower_button.setText("Update");
        update_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_borrower_buttonActionPerformed(evt);
            }
        });

        delete_borrower_button.setText("Delete");
        delete_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_borrower_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        item_doesnt_exist_message.setForeground(new java.awt.Color(255, 0, 51));

        jLabel8.setText("Surname");

        surname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_inputActionPerformed(evt);
            }
        });

        username_label.setText("Username");

        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrower_id_input)
                    .addComponent(check_member_exist_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address_input)
                    .addComponent(email_input)
                    .addComponent(phone_input)
                    .addComponent(accountNo_input)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(item_doesnt_exist_message, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addComponent(surname_input)
                    .addComponent(name_input)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(username_label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(message_from_server_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_input)
                    .addComponent(password_input)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(item_doesnt_exist_message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrower_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_member_exist_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountNo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message_from_server_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_borrower_button)
                    .addComponent(update_borrower_button)
                    .addComponent(delete_borrower_button)))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ACCOUNT BALANCE");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);

        jLabel9.setText("Item ID");

        add_item_button.setText("add item");
        add_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_buttonActionPerformed(evt);
            }
        });

        item_doesnt_exist.setForeground(new java.awt.Color(255, 0, 51));

        cancel_button.setText("cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        jButton3.setText("delete");

        finish_checkout_button.setText("finish");
        finish_checkout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_checkout_buttonActionPerformed(evt);
            }
        });

        jLabel12.setText("Items to checkout");

        find_item.setText("find item");
        find_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_itemActionPerformed(evt);
            }
        });

        checkout_items_display.setColumns(20);
        checkout_items_display.setRows(5);
        jScrollPane2.setViewportView(checkout_items_display);

        item_display.setColumns(20);
        item_display.setRows(5);
        checkout_items.setViewportView(item_display);

        jLabel11.setText("Total items:");

        total_items_display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        onloan_item_message.setForeground(new java.awt.Color(255, 0, 0));

        error_borrower_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        error_borrower_id.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(finish_checkout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item_doesnt_exist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(item_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(find_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(onloan_item_message))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(56, 56, 56)
                                .addComponent(total_items_display)
                                .addGap(18, 18, 18)
                                .addComponent(error_borrower_id, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(add_item_button))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(checkout_items))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_doesnt_exist, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find_item))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkout_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onloan_item_message)
                .addGap(37, 37, 37)
                .addComponent(add_item_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(total_items_display)
                    .addComponent(error_borrower_id))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(jButton3)
                    .addComponent(finish_checkout_button)))
        );

        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fine_amount.setText("TOTAL FINES TO PAY:");

        jLabel15.setText("Pay amount:");

        amount_to_pay_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_to_pay_inputActionPerformed(evt);
            }
        });

        pay_button.setText("Pay");
        pay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(amount_to_pay_input)
                        .addGap(18, 18, 18)
                        .addComponent(pay_button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fine_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(fine_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_to_pay_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_button))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_borrower_buttonActionPerformed
        // TODO add your handling code here:
        int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String message_confirmation = library.removeAccount(borrowerID);
        message_from_server_label.setText(message_confirmation);

    }//GEN-LAST:event_delete_borrower_buttonActionPerformed

    private void update_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_borrower_buttonActionPerformed
        // TODO add your handling code here:
       int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String name = name_input.getText();
        String surname = surname_input.getText();
        String address = address_input.getText();
        String email = email_input.getText();
        int phone = Integer.parseInt(phone_input.getText());
        int accountNo = Integer.parseInt(accountNo_input.getText());
        String username = username_input.getText();
        String password = password_input.getText();
        Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
        String message_from_server = library.updateBorrower(borrower);
        message_from_server_label.setText(message_from_server);
        borrower_id_input.setText("");
        name_input.setText("");
        surname_input.setText("");
        address_input.setText("");
        email_input.setText("");
        phone_input.setText("");
        accountNo_input.setText("");
        username_input.setText("");
        password_input.setText("");

    }//GEN-LAST:event_update_borrower_buttonActionPerformed

    private String getCurrentDate(){
        Date date = new Date();
        String strDateFormat = "dd:mm:y";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        return formattedDate;
        
    }
    private void add_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_borrower_buttonActionPerformed
        // TODO add your handling code here:
        int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String name = name_input.getText();
        String surname = surname_input.getText();
        String address = address_input.getText();
        String email = email_input.getText();
        int phone = Integer.parseInt(phone_input.getText());
        int accountNo = Integer.parseInt(accountNo_input.getText());
        String username = username_input.getText();
        String password = password_input.getText();
        String openingDate = this.getCurrentDate();
        int openingBalance = 0;
        Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
        Account account = new Account(accountNo, openingBalance, openingDate, borrower);
        String message_from_server = library.addAccount(account);
        message_from_server_label.setText(message_from_server);
        borrower_id_input.setText("");
        name_input.setText("");
        surname_input.setText("");
        address_input.setText("");
        email_input.setText("");
        phone_input.setText("");
        accountNo_input.setText("");
        username_input.setText("");
        password_input.setText("");

    }//GEN-LAST:event_add_borrower_buttonActionPerformed

    private void accountNo_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNo_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNo_inputActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void check_member_exist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_member_exist_buttonActionPerformed
        // TODO add your handling code here:
        message_from_server_label.setText("");
        String borrowerIDString = borrower_id_input.getText();
        if ("".equals(borrowerIDString)){
            message_from_server_label.setText("enter unique borrower ID");
        }
        else if (borrowerIDString.matches(".*[a-z].*")) { 
         // Do something
          message_from_server_label.setText("borrowerID must only contain numbers");
        }
        else{
            int borrower_id = Integer.parseInt(borrower_id_input.getText());        
            ArrayList<Borrower> borrowerlist = library.getBorrowerInformation(borrower_id);
            if (borrowerlist.size()==0){
                item_doesnt_exist_message.setText("borrower account doesn't exist");
                name_input.setText("");
                surname_input.setText("");
                address_input.setText("");
                email_input.setText("");
                phone_input.setText("");
                accountNo_input.setText("");
                username_input.setText("");
                password_input.setText("");
            }else{
                Borrower borrower = borrowerlist.get(0);
                item_doesnt_exist_message.setText("");
                name_input.setText(borrower.getName());
                surname_input.setText(borrower.getSurname());
                address_input.setText(borrower.getAddress());            
                email_input.setText(borrower.getEmail());
                phone_input.setText(Integer.toString(borrower.getPhone()));
                accountNo_input.setText(Integer.toString(borrower.getAccountNo()));
                username_input.setText(borrower.getUsername());
                password_input.setText(borrower.getPassword());
                accountDetails = account.getAccountDetails(borrower.getAccountNo()); //Hashmp contains account number and 
                //display balance
                ArrayList accountInfo = accountDetails.get(borrower.getAccountNo());
                balance = Integer.parseInt(accountInfo.get(0).toString());
                fine_amount.setText("TOTAL FINES TO PAY: $" + Integer.toString(balance));
                

            }
        }

    }//GEN-LAST:event_check_member_exist_buttonActionPerformed

    private void surname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_inputActionPerformed

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

//    private String getDueDate(){
//      int loanPeriod = 0;
//        if (item.getType()=="book"){
//           loanPeriod=3;
//        }
//        else{
//            loanPeriod = 2;
//        }
//      Date d1 = new Date();
//      Calendar cl = Calendar. getInstance();
//      cl.setTime(d1);
//      cl. add(Calendar.DATE, loanPeriod);
//      String duedate = cl.getTime().toString();
//      return duedate;
//    }
    
    private String getDateNow(){
        Date date = new Date();
        String strDateFormat = "yyyy-MM-dd";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        return formattedDate;       
    }
    
    private String getDueDate() throws ParseException{
        String currentDate = getDateNow();
         int loanPeriod = 0;
        if (item.getType()=="book"){
           loanPeriod=21;
        }
        else{
            loanPeriod = 14;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat( "yyyy-MM-dd" );
        Calendar cal = Calendar.getInstance();
        cal.setTime(dateFormat.parse(currentDate));
        cal.add( Calendar.DATE, loanPeriod );
        String duedate = cal.getTime().toString();
        return duedate;
    }
    
    private void finish_checkout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_checkout_buttonActionPerformed
        // TODO add your handling code here:

        //initialize due date
        if ("".equals(borrower_id_input.getText())){
            error_borrower_id.setText("please enter valid borrower_id");
        }

        else if (itemlist.isEmpty()){
            error_borrower_id.setText("error: no items  to check out");
        }
        else{
            int borrower_id = Integer.parseInt(borrower_id_input.getText());
            ArrayList<Borrower> borrowerlist = library.getBorrowerInformation(borrower_id);
            if (borrowerlist.size()==0){
                error_borrower_id.setText("borrower account doesn't exist");
            }
            else{
                String duedate = "";
                try {
                    duedate = this.getDueDate();
                } catch (ParseException ex) {
                    Logger.getLogger(OverdueActivity.class.getName()).log(Level.SEVERE, null, ex);
                }

                //create new Loan         //add items and borrower to loan
                Library library = new Library();
                Loan loan = new Loan(borrower_id, itemlist, duedate, "Loan");
                library.addLoan(loan);


                //change status to on loan
                for (Item item : itemlist){
                    item.updateStatus(item.getIdentifier(), "OUT");
                }
                checkout_complete_dialog.setVisible(true);
            }
        }
        
        
    }//GEN-LAST:event_finish_checkout_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        itemlist = new ArrayList<Item>(){};
        checkout_items_display.setText("");
        total_items_display.setText("");
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_complete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_complete_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        checkout_complete_dialog.setVisible(false);
        new MenuActivity().setVisible(true);
    }//GEN-LAST:event_ok_complete_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
        new MenuActivity().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void find_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_itemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        item_display.setText("");
        item_doesnt_exist.setText("");
        onloan_item_message.setText("");

        String item_id = item_id_input.getText();
        System.out.print(item_id);
        item = library.getItem(item_id);
        if (item==null){
            item_doesnt_exist.setText("item doesn't exist");
            item_display.setText("");

        }else{
            item_doesnt_exist_message.setText("");
            String item_info = item.itemToString();
            //            String title = item.getTitle();
            //            String author = item.getAuthor();
            //            String keywords = item.getKeywords();
            //            String type = item.getType();
            //            String status = item.getStatus();
            //            String item_info = "Title: " + title + "\nAuthor: " + author + "\nKeywords: " + keywords + "\nType: " + type + "\nStatus: " + status;
            item_display.setText(item_info);

        }
    }//GEN-LAST:event_find_itemActionPerformed

    private void add_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_buttonActionPerformed
        // TODO add your handling code here:
        error_borrower_id.setText("");
        if ("OUT".equals(item.getStatus())){

            onloan_item_message.setText("cannot add: item is on loan");
        }
        else if ("RESERVE".equals(item.getStatus())){
            onloan_item_message.setText("cannot add: item has been reserved");

        }
        else {
            System.out.print(item.getStatus());
            itemlist.add(item);
            checkout_items_display.append(item.checkoutItemToString()+"\n");
            int totalItems = itemlist.size();
            total_items_display.setText(Integer.toString(totalItems));
        }

    }//GEN-LAST:event_add_item_buttonActionPerformed

    private void amount_to_pay_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_to_pay_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_to_pay_inputActionPerformed

    private void pay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_buttonActionPerformed
        int accountNo = Integer.parseInt(accountNo_input.getText());
        account.creditAmount(accountNo, Integer.parseInt(amount_to_pay_input.getText()));
        int balance = account.getBalance(accountNo);
        fine_amount.setText("TOTAL FINES TO PAY: $" + Integer.toString(balance));
    }//GEN-LAST:event_pay_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverdueActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverdueActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverdueActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverdueActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverdueActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNo_input;
    private javax.swing.JButton add_borrower_button;
    private javax.swing.JButton add_item_button;
    private javax.swing.JTextField address_input;
    private javax.swing.JTextField amount_to_pay_input;
    private javax.swing.JTextField borrower_id_input;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton check_member_exist_button;
    private javax.swing.JDialog checkout_complete_dialog;
    private javax.swing.JScrollPane checkout_items;
    private javax.swing.JTextArea checkout_items_display;
    private javax.swing.JButton delete_borrower_button;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel error_borrower_id;
    private javax.swing.JButton find_item;
    private javax.swing.JLabel fine_amount;
    private javax.swing.JButton finish_checkout_button;
    private javax.swing.JTextArea item_display;
    private javax.swing.JLabel item_doesnt_exist;
    private javax.swing.JLabel item_doesnt_exist_message;
    private javax.swing.JTextField item_id_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel message_from_server_label;
    private javax.swing.JTextField name_input;
    private javax.swing.JButton ok_complete_button;
    private javax.swing.JLabel onloan_item_message;
    private javax.swing.JTextField password_input;
    private javax.swing.JButton pay_button;
    private javax.swing.JTextField phone_input;
    private javax.swing.JTextField surname_input;
    private javax.swing.JLabel total_items_display;
    private javax.swing.JButton update_borrower_button;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
