/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import core.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author 14400
 */
public class UserActivity extends javax.swing.JFrame {

    Library library = new Library();
    /**
     * Creates new form ItemsActivity
     */
    public UserActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        check_member_exist_button = new javax.swing.JButton();
        borrower_id_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accountNo_input = new javax.swing.JTextField();
        add_borrower_button = new javax.swing.JButton();
        update_borrower_button = new javax.swing.JButton();
        delete_borrower_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        address_input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        item_doesnt_exist_message = new javax.swing.JLabel();
        message_from_server_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        surname_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        password_input = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setEnabled(false);

        check_member_exist_button.setText("check if member exists");
        check_member_exist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_member_exist_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Borrower ID");

        jLabel2.setText("Name");

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone");

        jLabel4.setText("AccountNo");

        accountNo_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNo_inputActionPerformed(evt);
            }
        });

        add_borrower_button.setText("Add");
        add_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_borrower_buttonActionPerformed(evt);
            }
        });

        update_borrower_button.setText("Update");
        update_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_borrower_buttonActionPerformed(evt);
            }
        });

        delete_borrower_button.setText("Delete");
        delete_borrower_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_borrower_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        item_doesnt_exist_message.setForeground(new java.awt.Color(255, 0, 51));

        message_from_server_label.setForeground(new java.awt.Color(51, 204, 0));

        jLabel8.setText("Surname");

        surname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_inputActionPerformed(evt);
            }
        });

        username_label.setText("Username");

        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrower_id_input)
                    .addComponent(check_member_exist_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address_input)
                    .addComponent(email_input)
                    .addComponent(phone_input)
                    .addComponent(accountNo_input)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(item_doesnt_exist_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(add_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(update_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(delete_borrower_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(surname_input)
                    .addComponent(name_input)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(username_label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(message_from_server_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_input)
                    .addComponent(password_input)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(item_doesnt_exist_message, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrower_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_member_exist_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountNo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message_from_server_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_borrower_button)
                    .addComponent(update_borrower_button)
                    .addComponent(delete_borrower_button)))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ADD/UPDATE/DELETE BORROWERS");

        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_borrower_buttonActionPerformed
        // TODO add your handling code here:
        int borrowerID = Integer.parseInt(borrower_id_input.getText());
        String message_confirmation = library.removeAccount(borrowerID);
        message_from_server_label.setText(message_confirmation);

    }//GEN-LAST:event_delete_borrower_buttonActionPerformed

    private void update_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_borrower_buttonActionPerformed
        // TODO add your handling code here:
               String borrowerIDString = borrower_id_input.getText();
        if ("".equals(borrowerIDString)){
            message_from_server_label.setText("enter unique borrower ID");
        }
        else if (borrowerIDString.matches(".*[a-z].*")) { 
         // Do something
          message_from_server_label.setText("borrowerID must only contain numbers");
        }
        else{
            int borrowerID = Integer.parseInt(borrower_id_input.getText());
            String name = name_input.getText();
            String surname = surname_input.getText();
            String address = address_input.getText();
            String email = email_input.getText();
            int phone = Integer.parseInt(phone_input.getText());
            int accountNo = Integer.parseInt(accountNo_input.getText());
            String username = username_input.getText();
            String password = password_input.getText();
            Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
            String message_from_server = library.updateBorrower(borrower);
            message_from_server_label.setText(message_from_server);
            borrower_id_input.setText("");
            name_input.setText("");
            surname_input.setText("");
            address_input.setText("");
            email_input.setText("");
            phone_input.setText("");
            accountNo_input.setText("");
            username_input.setText("");
            password_input.setText("");
        }

    }//GEN-LAST:event_update_borrower_buttonActionPerformed

    private String getCurrentDate(){
        Date date = new Date();
        String strDateFormat = "dd:mm:y";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate = dateFormat.format(date);
        return formattedDate;       
    }
    
    private void add_borrower_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_borrower_buttonActionPerformed
        // TODO add your handling code here:
        String borrowerIDString = borrower_id_input.getText();
        if ("".equals(borrowerIDString)){
            message_from_server_label.setText("enter unique borrower ID");
        }
        else if (borrowerIDString.matches(".*[a-z].*")) { 
         // Do something
          message_from_server_label.setText("borrowerID must only contain numbers");
        }
        else{

            int borrowerID = Integer.parseInt(borrower_id_input.getText());
            String name = name_input.getText();
            String surname = surname_input.getText();
            String address = address_input.getText();
            String email = email_input.getText();
            int phone = Integer.parseInt(phone_input.getText());
            int accountNo = Integer.parseInt(accountNo_input.getText());
            String username = username_input.getText();
            String password = password_input.getText();
            String openingDate = this.getCurrentDate();
            int openingBalance = 0;
            Borrower borrower = new Borrower(borrowerID, name, surname, address, email, phone, accountNo, username, password);
            Account account = new Account(accountNo, openingBalance, openingDate, borrower);
            String message_from_server = library.addAccount(account);
            message_from_server_label.setText(message_from_server);
            borrower_id_input.setText("");
            name_input.setText("");
            surname_input.setText("");
            address_input.setText("");
            email_input.setText("");
            phone_input.setText("");
            accountNo_input.setText("");
            username_input.setText("");
            password_input.setText("");
        }

    }//GEN-LAST:event_add_borrower_buttonActionPerformed

    private void accountNo_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNo_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNo_inputActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void check_member_exist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_member_exist_buttonActionPerformed
        // TODO add your handling code here:
        message_from_server_label.setText("");
        String borrowerIDString = borrower_id_input.getText();
        if ("".equals(borrowerIDString)){
            message_from_server_label.setText("enter unique borrower ID");
        }
        else if (borrowerIDString.matches(".*[a-z].*")) { 
         // Do something
          message_from_server_label.setText("borrowerID must only contain numbers");
        }
        else{
            int borrower_id = Integer.parseInt(borrower_id_input.getText());        
            ArrayList<Borrower> borrowerlist = library.getBorrowerInformation(borrower_id);
            if (borrowerlist.size()==0){
                item_doesnt_exist_message.setText("borrower account doesn't exist");
                name_input.setText("");
                surname_input.setText("");
                address_input.setText("");
                email_input.setText("");
                phone_input.setText("");
                accountNo_input.setText("");
                username_input.setText("");
                password_input.setText("");
            }else{
                Borrower borrower = borrowerlist.get(0);
                item_doesnt_exist_message.setText("");
                name_input.setText(borrower.getName());
                surname_input.setText(borrower.getSurname());
                address_input.setText(borrower.getAddress());            
                email_input.setText(borrower.getEmail());
                phone_input.setText(Integer.toString(borrower.getPhone()));
                accountNo_input.setText(Integer.toString(borrower.getAccountNo()));
                username_input.setText(borrower.getUsername());
                password_input.setText(borrower.getPassword());

            }
        }

    }//GEN-LAST:event_check_member_exist_buttonActionPerformed

    private void surname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_inputActionPerformed

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
        new MenuActivity().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNo_input;
    private javax.swing.JButton add_borrower_button;
    private javax.swing.JTextField address_input;
    private javax.swing.JTextField borrower_id_input;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton check_member_exist_button;
    private javax.swing.JButton delete_borrower_button;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel item_doesnt_exist_message;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message_from_server_label;
    private javax.swing.JTextField name_input;
    private javax.swing.JTextField password_input;
    private javax.swing.JTextField phone_input;
    private javax.swing.JTextField surname_input;
    private javax.swing.JButton update_borrower_button;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
